{% set name = "dropboxdrivefs" %}
{% set version = "1.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "644ad6e4be85f5a637da7246f797af88a1af3e4f658e972b42b559486c81036b"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - dropbox
    - fsspec
    - pip
    - python
    - requests
  run:
    - dropbox
    - fsspec
    - python
    - requests

test:
  imports:
    - dropboxdrivefs

about:
  home: "The package home page"
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "LICENSE"
  summary: "Dropbox implementation for fsspec module"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - MarineChap
